# Generated by Django 4.1.5 on 2023-02-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                ("tenant_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("bhk", models.IntegerField()),
                ("age", models.IntegerField()),
                ("phone_number", models.CharField(max_length=10)),
                ("rent", models.CharField(max_length=10)),
                ("rent_date", models.DateField()),
                ("adhar_num", models.CharField(max_length=12)),
                ("adhar_pic", models.ImageField(upload_to="adhar_card")),
                ("property_pic", models.ImageField(upload_to="Propery_image")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
