# Generated by Django 4.1.5 on 2023-02-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetail",
            name="adhar_pic",
            field=models.ImageField(null=True, upload_to="adhar_card"),
        ),
        migrations.AlterField(
            model_name="propertydetail",
            name="property_pic",
            field=models.ImageField(null=True, upload_to="Propery_image"),
        ),
        migrations.AlterField(
            model_name="propertydetail",
            name="rent_date",
            field=models.DateField(null=True),
        ),
    ]
