# Generated by Django 4.1.5 on 2023-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0002_alter_propertydetail_adhar_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetail",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
