# Generated by Django 4.1.6 on 2023-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propertyManager", "0003_propertydetail_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydetail",
            name="email",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
