# Generated by Django 4.1.6 on 2023-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_name",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                (
                    "tenant_name",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("property_age", models.IntegerField(default=None, null=True)),
                (
                    "rent_amount",
                    models.CharField(default=None, max_length=12, null=True),
                ),
                ("rent_date", models.DateField()),
                ("adhar_number", models.CharField(max_length=12)),
                ("adhar_image", models.ImageField(upload_to="adhar_pic")),
                ("property_image", models.ImageField(upload_to="property_image")),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
