# Generated by Django 4.1.6 on 2023-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property_manager", "0002_alter_property_rent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="adhar_number",
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
