# Generated by Django 4.1.6 on 2023-02-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property_manager", "0003_alter_property_adhar_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="adhar_image",
            field=models.ImageField(default=None, null=True, upload_to="adhar_pic"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_image",
            field=models.ImageField(
                default=None, null=True, upload_to="property_image"
            ),
        ),
    ]
